/**
 * @domain marketing
 * @layer ui
 * @responsibility UI route entrypoint for /privacy
 */

import type { Metadata } from "next"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { routes } from "@/lib/routes"
import Link from "next/link"
import { Shield, Lock, CheckCircle2, Database } from "lucide-react"

export const metadata: Metadata = {
  title: "Privacy Policy - AFENDA",
  description: "Privacy policy, data protection, and security practices built on Neon serverless PostgreSQL with SOC 2, HIPAA, and GDPR compliance",
}

export default function PrivacyPage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-16">
      <div className="w-full">
        <Card>
          <CardHeader className="space-y-3 text-center">
            <CardTitle className="text-2xl">Privacy Policy</CardTitle>
            <CardDescription>
              Effective date: {new Date().toLocaleDateString()} · Clear commitments for data use, protection, and privacy rights.
            </CardDescription>
            <div className="flex flex-wrap justify-center gap-2">
              <Badge variant="outline" className="gap-1">
                <Shield className="h-3 w-3" aria-hidden="true" /> SOC 2 Type II
              </Badge>
              <Badge variant="outline" className="gap-1">
                <Lock className="h-3 w-3" aria-hidden="true" /> HIPAA
              </Badge>
              <Badge variant="outline" className="gap-1">
                <CheckCircle2 className="h-3 w-3" aria-hidden="true" /> GDPR
              </Badge>
              <Badge variant="outline" className="gap-1">
                <Database className="h-3 w-3" aria-hidden="true" /> Neon PostgreSQL
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="grid gap-8">
            <section className="grid gap-4 md:grid-cols-3">
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">We Do Not Sell Data</h3>
                <p className="text-muted-foreground mt-2">
                  Personal data is never sold or monetized. Processing is limited to service delivery and compliance needs.
                </p>
              </div>
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">Encrypted by Default</h3>
                <p className="text-muted-foreground mt-2">
                  AES-256 encryption at rest and TLS 1.3 in transit are standard for all customer data.
                </p>
              </div>
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">Retention Controls</h3>
                <p className="text-muted-foreground mt-2">
                  Account data is retained while active and removed within 30 days after closure, subject to legal obligations.
                </p>
              </div>
            </section>
            <div className="space-y-4 text-sm">
              <section>
                <h3 className="font-semibold">Information We Collect</h3>
                <p className="text-muted-foreground">
                  We collect information you provide directly (such as account details and support requests) and
                  information generated by service usage (such as audit logs and operational metadata). All data is stored
                  securely in Neon serverless PostgreSQL with encryption controls.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Data Storage & Infrastructure</h3>
                <p className="text-muted-foreground">
                  Your data is hosted on <strong>Neon.tech</strong> serverless PostgreSQL in the <strong>ap-southeast-1 (Singapore)</strong> region.
                  Our infrastructure is SOC 2 Type II certified and HIPAA compliant with:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li>AES-256 encryption at rest</li>
                  <li>TLS 1.3 encryption in transit</li>
                  <li>Hourly automated backups with 7-day point-in-time recovery</li>
                  <li>Connection pooling with 1000+ concurrent connections</li>
                  <li>Auto-scaling compute (0.25-2 CU)</li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">How We Use Your Information</h3>
                <p className="text-muted-foreground">
                  We use collected information to deliver and operate the service, maintain security, improve performance,
                  respond to support requests, and meet legal or compliance requirements.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Legal Bases for Processing</h3>
                <p className="text-muted-foreground">
                  Where applicable, we process data based on contractual necessity, legitimate interests in operating a secure platform,
                  compliance with legal obligations, and user consent when required.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Information Sharing</h3>
                <p className="text-muted-foreground">
                  We do not sell personal information. We share data only with vetted subprocessors required to operate the service:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>Neon.tech:</strong> Database hosting (SOC 2, HIPAA)</li>
                  <li><strong>Better Auth:</strong> Authentication services (OAuth 2.0)</li>
                  <li><strong>AWS:</strong> Cloud infrastructure provider</li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">Data Security</h3>
                <p className="text-muted-foreground">
                  We implement layered security controls, including:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li>Encryption: AES-256 at rest, TLS 1.3 in transit</li>
                  <li>Authentication: OAuth 2.0 (Google, GitHub) with JWT</li>
                  <li>Access Control: Role-based (RBAC) and row-level security (RLS)</li>
                  <li>Audit Logging: 90-day retention with full activity tracking</li>
                  <li>Backup: Hourly snapshots with 7-day recovery window</li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">Your Rights (GDPR & CCPA)</h3>
                <p className="text-muted-foreground">
                  You have the right to:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>Access:</strong> Request a copy of your personal data</li>
                  <li><strong>Rectification:</strong> Update or correct your information</li>
                  <li><strong>Erasure:</strong> Request deletion of your data (&quot;right to be forgotten&quot;)</li>
                  <li><strong>Portability:</strong> Export your data in a machine-readable format</li>
                  <li><strong>Objection:</strong> Opt-out of certain data processing activities</li>
                </ul>
                <p className="text-muted-foreground mt-2">
                  Contact <a href="mailto:privacy@nexuscanon.com" className="underline">privacy@nexuscanon.com</a> to exercise your rights.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">International Transfers</h3>
                <p className="text-muted-foreground">
                  Data may be processed in the regions where our infrastructure and subprocessors operate, including Singapore. We use
                  appropriate safeguards for cross-border transfers where required.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Data Retention</h3>
                <p className="text-muted-foreground">
                  We retain your data for as long as your account is active or as needed to provide services.
                  Deleted data is purged within 30 days. Audit logs are retained for 90 days for compliance purposes.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Compliance & Certifications</h3>
                <p className="text-muted-foreground">
                  Our infrastructure meets the following standards:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>SOC 2 Type II:</strong> Annual third-party audit</li>
                  <li><strong>HIPAA:</strong> Business Associate Agreement (BAA) available</li>
                  <li><strong>GDPR:</strong> EU data protection compliance</li>
                  <li><strong>CCPA:</strong> California privacy rights honored</li>
                </ul>
              </section>
            </div>
            <div className="flex flex-col gap-2">
              <Button asChild>
                <Link href={routes.ui.orchestra.root()}>Go to AFENDA</Link>
              </Button>
              <Button asChild variant="outline">
                <Link href="/security">View Security Declaration</Link>
              </Button>
              <Button asChild variant="ghost">
                <Link href={routes.ui.marketing.terms()}>Terms of Service</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

